# Generated by Django 4.2.27 on 2025-12-03 05:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.infrastructure.persistence.models.content


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcemodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resourcemodel',
            name='file_url',
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='document_file',
            field=models.FileField(blank=True, help_text='Upload tài liệu: PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX, TXT, ZIP, RAR', null=True, upload_to=src.infrastructure.persistence.models.content.resource_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'zip', 'rar'])], verbose_name='File tài liệu'),
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL liên kết bên ngoài', null=True, verbose_name='URL liên kết'),
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Tự động tính khi upload', null=True, verbose_name='Kích thước file (bytes)'),
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='text_content',
            field=models.TextField(blank=True, help_text='Nội dung văn bản hiển thị trực tiếp', null=True, verbose_name='Nội dung văn bản'),
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video: MP4, WEBM, OGG, MOV, AVI, MKV', null=True, upload_to=src.infrastructure.persistence.models.content.video_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'avi', 'mkv'])], verbose_name='File video'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='end_date',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='start_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Sắp diễn ra'), ('ONGOING', 'Đang diễn ra'), ('COMPLETED', 'Đã hoàn thành')], default='UPCOMING', editable=False, help_text='Trạng thái được tính tự động dựa trên ngày bắt đầu và kết thúc', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='persistence.subjectmodel', verbose_name='Môn học'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tên khóa học'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Thời lượng video tính bằng giây', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thời lượng (giây)'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='persistence.lessonmodel', verbose_name='Bài học'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='type',
            field=models.CharField(choices=[('DOCUMENT', 'Tài liệu'), ('VIDEO', 'Video'), ('LINK', 'Liên kết'), ('TEXT', 'Văn bản')], max_length=20, verbose_name='Loại tài liệu'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='video_url',
            field=models.URLField(blank=True, help_text='Hoặc nhập URL video (YouTube, Vimeo, etc.)', null=True, verbose_name='URL video'),
        ),
        # Removed AlterModelTable for userprofilemodel - table already named correctly
    ]
