# Generated by Django 4.2.27 on 2025-12-15 04:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persistence', '0002_update_resource_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbankmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='question_bank',
        ),
        migrations.AlterUniqueTogether(
            name='userassignmentprogressmodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userassignmentprogressmodel',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='userassignmentprogressmodel',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogressmodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercourseprogressmodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourseprogressmodel',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogressmodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userlessonprogressmodel',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userlessonprogressmodel',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userresourceprogressmodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userresourceprogressmodel',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='userresourceprogressmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm tối đa'),
        ),
        migrations.AddField(
            model_name='attemptmodel',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Nhận xét của giảng viên'),
        ),
        migrations.AddField(
            model_name='attemptmodel',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='File nộp bài'),
        ),
        migrations.AddField(
            model_name='attemptmodel',
            name='submitted_text',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung nộp'),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='attempts_allowed',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lần làm cho phép'),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='end_at',
            field=models.DateTimeField(verbose_name='Thời gian đóng'),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='instructions',
            field=models.TextField(blank=True, help_text='Hướng dẫn làm bài cho học viên', null=True, verbose_name='Hướng dẫn'),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='persistence.lessonmodel', verbose_name='Bài học'),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='start_at',
            field=models.DateTimeField(verbose_name='Thời gian mở'),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Để trống nếu không giới hạn', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Giới hạn thời gian (phút)'),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='type',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('FILE_UPLOAD', 'Nộp file')], default='FILE_UPLOAD', max_length=20, verbose_name='Loại bài tập'),
        ),
        migrations.AlterField(
            model_name='attemptmodel',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='persistence.assignmentmodel', verbose_name='Bài tập'),
        ),
        migrations.AlterField(
            model_name='attemptmodel',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm'),
        ),
        migrations.AlterField(
            model_name='attemptmodel',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bắt đầu lúc'),
        ),
        migrations.AlterField(
            model_name='attemptmodel',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Đang làm'), ('SUBMITTED', 'Đã nộp'), ('GRADED', 'Đã chấm điểm')], default='IN_PROGRESS', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='attemptmodel',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nộp lúc'),
        ),
        migrations.AlterField(
            model_name='attemptmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Học viên'),
        ),
        # Removed AlterModelTable - table already correctly named
        migrations.DeleteModel(
            name='AttemptDetailModel',
        ),
        migrations.DeleteModel(
            name='QuestionBankModel',
        ),
        migrations.DeleteModel(
            name='QuestionModel',
        ),
        migrations.DeleteModel(
            name='UserAssignmentProgressModel',
        ),
        migrations.DeleteModel(
            name='UserCourseProgressModel',
        ),
        migrations.DeleteModel(
            name='UserLessonProgressModel',
        ),
        migrations.DeleteModel(
            name='UserResourceProgressModel',
        ),
    ]
