# Generated by Django 4.2.27 on 2025-12-15 04:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_remove_unused_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmodel',
            name='show_result',
            field=models.BooleanField(default=True, help_text='Cho phép học viên xem kết quả sau khi nộp bài', verbose_name='Hiển thị kết quả'),
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='shuffle_answers',
            field=models.BooleanField(default=False, help_text='Trộn ngẫu nhiên thứ tự đáp án cho mỗi câu hỏi', verbose_name='Trộn đáp án'),
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Trộn ngẫu nhiên thứ tự câu hỏi cho mỗi lần làm', verbose_name='Trộn câu hỏi'),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='type',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('FILE_UPLOAD', 'Nộp file')], default='QUIZ', max_length=20, verbose_name='Loại bài tập'),
        ),
        # Removed AlterModelTable - table already correctly named
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('option_a', models.CharField(max_length=500, verbose_name='Đáp án A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Đáp án B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Đáp án C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Đáp án D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Đáp án đúng')),
                ('explanation', models.TextField(blank=True, help_text='Giải thích đáp án đúng (hiển thị sau khi nộp bài)', null=True, verbose_name='Giải thích')),
                ('level', models.CharField(choices=[('EASY', 'Dễ'), ('MEDIUM', 'Trung bình'), ('HARD', 'Khó')], default='MEDIUM', max_length=20, verbose_name='Độ khó')),
                ('points', models.DecimalField(decimal_places=2, default=1, help_text='Điểm cho câu hỏi này', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='persistence.assignmentmodel', verbose_name='Bài tập')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Câu hỏi',
                'db_table': 'questions',
                'ordering': ['assignment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AttemptDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='Đáp án đã chọn')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Đúng/Sai')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Thời gian làm câu này (giây)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Thời gian (giây)')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm trả lời')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='persistence.attemptmodel', verbose_name='Lần làm bài')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_details', to='persistence.questionmodel', verbose_name='Câu hỏi')),
            ],
            options={
                'verbose_name': 'Chi tiết câu trả lời',
                'verbose_name_plural': 'Chi tiết câu trả lời',
                'db_table': 'attempt_details',
                'ordering': ['attempt', 'question__order'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
