# Generated by Django 4.2.27 on 2025-12-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_restore_questions_and_attempt_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptdetailmodel',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='attemptdetailmodel',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='level',
        ),
    ]
