# Generated by Django 4.2.27 on 2025-12-15 07:52

import django.core.validators
from django.db import migrations, models
import src.infrastructure.persistence.models.content
import src.infrastructure.persistence.validators


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0006_add_video_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptmodel',
            name='submitted_file',
            field=models.FileField(blank=True, help_text='File nộp bài: PDF, DOC, DOCX, PPT, XLS, ZIP, RAR, JPG, PNG, PY, JAVA, etc. (tối đa 50MB)', null=True, upload_to='submissions/', validators=[src.infrastructure.persistence.validators.SubmissionFileValidator()], verbose_name='File nộp bài'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='document_file',
            field=models.FileField(blank=True, help_text='Upload tài liệu: PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX, TXT, ZIP, RAR (tối đa 20MB)', null=True, upload_to=src.infrastructure.persistence.models.content.resource_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'zip', 'rar']), src.infrastructure.persistence.validators.DocumentFileValidator()], verbose_name='File tài liệu'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video: MP4, WEBM, OGG, MOV, AVI, MKV, WMV, FLV, M4V (tối đa 500MB)', null=True, upload_to=src.infrastructure.persistence.models.content.video_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'avi', 'mkv', 'wmv', 'flv', 'm4v']), src.infrastructure.persistence.validators.VideoFileValidator()], verbose_name='File video'),
        ),
        # Bỏ qua AlterModelTable vì bảng accounts_userprofile đã tồn tại
        # migrations.AlterModelTable(
        #     name='userprofilemodel',
        #     table='accounts_userprofile',
        # ),
    ]
