# Generated by Django 4.2.27 on 2025-12-17 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persistence', '0007_alter_attemptmodel_submitted_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bình luận', 'verbose_name_plural': 'Bình luận'},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID đối tượng'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='target_type',
            field=models.CharField(blank=True, choices=[('LESSON', 'Bài học'), ('ASSIGNMENT', 'Bài tập')], max_length=20, null=True, verbose_name='Loại đối tượng'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID đối tượng liên quan'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='related_object_type',
            field=models.CharField(blank=True, help_text='Ví dụ: lesson, assignment', max_length=50, null=True, verbose_name='Loại đối tượng liên quan'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='type',
            field=models.CharField(choices=[('LESSON_CREATED', 'Bài học mới'), ('ASSIGNMENT_CREATED', 'Bài tập mới'), ('ASSIGNMENT_DEADLINE', 'Bài tập sắp đến hạn'), ('ASSIGNMENT_GRADED', 'Bài tập đã được chấm'), ('GENERAL', 'Thông báo chung')], default='GENERAL', max_length=50, verbose_name='Loại thông báo'),
        ),
        migrations.AddField(
            model_name='useractivitylogmodel',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID đối tượng'),
        ),
        migrations.AddField(
            model_name='useractivitylogmodel',
            name='target_type',
            field=models.CharField(blank=True, help_text='Ví dụ: lesson, assignment, attempt', max_length=50, null=True, verbose_name='Loại đối tượng'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='persistence.lessonmodel', verbose_name='Bài học (deprecated)'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='persistence.commentmodel', verbose_name='Bình luận cha'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Đã đọc'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='message',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='useractivitylogmodel',
            name='action_type',
            field=models.CharField(choices=[('VIEW_LESSON', 'Xem bài học'), ('START_ATTEMPT', 'Bắt đầu làm bài'), ('SUBMIT_ATTEMPT', 'Nộp bài'), ('VIEW_RESULT', 'Xem kết quả bài làm'), ('VIEW_RESOURCE', 'Xem tài liệu'), ('PLAY_VIDEO', 'Phát video'), ('VIEW_COURSE', 'Xem khóa học'), ('VIEW_MODULE', 'Xem chương'), ('COMMENT', 'Bình luận'), ('DOWNLOAD_RESOURCE', 'Tải tài liệu')], max_length=50, verbose_name='Loại hành động'),
        ),
        migrations.AlterField(
            model_name='useractivitylogmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='persistence.coursemodel', verbose_name='Khóa học (deprecated)'),
        ),
        migrations.AlterField(
            model_name='useractivitylogmodel',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Thông tin bổ sung: điểm số, attempt_id, etc.', null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='useractivitylogmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='useractivitylogmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddIndex(
            model_name='commentmodel',
            index=models.Index(fields=['target_type', 'target_id'], name='comments_target__71256e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmodel',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='notificatio_related_1106fe_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylogmodel',
            index=models.Index(fields=['user', '-timestamp'], name='user_activi_user_id_0a625a_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylogmodel',
            index=models.Index(fields=['target_type', 'target_id'], name='user_activi_target__b9bbb4_idx'),
        ),
        # Removed AlterModelTable for userprofilemodel - table already exists with correct name
    ]
